# Generated by Django 4.2.4 on 2023-09-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservation_time',
            field=models.TimeField(null=True),
        ),
    ]
